@startuml sec-autenticacion
title Secuencia — Autenticación de Usuario (Adapter, RNF-004)

actor Funcionario
participant "Sistema SGR" as SGR
participant AutenticacionAdapter
participant DirectorioInstitucionalClient as Directorio

Funcionario -> SGR: login(usuario, clave)
activate SGR
SGR -> AutenticacionAdapter: autenticar(usuario, clave)
activate AutenticacionAdapter
AutenticacionAdapter -> Directorio: validarCredencialLDAP(dn, pwd)
activate Directorio
Directorio --> AutenticacionAdapter: LDAPResult
deactivate Directorio
AutenticacionAdapter -> AutenticacionAdapter: traducir resultado\na Funcionario + roles
AutenticacionAdapter --> SGR: Funcionario autenticado
deactivate AutenticacionAdapter
SGR --> Funcionario: acceso concedido
deactivate SGR

@enduml
